'use client'

import { Header } from '@/components'
import './globals.css'
import { ContextApi, CreateContext } from '@/store/context'


// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }
import { Roboto } from 'next/font/google'
// import { IContext } from '@/types'
// import { useContext, useEffect } from 'react'
// import Cookies from 'js-cookie'
const roboto = Roboto({ subsets: ['latin'], weight: ['500', '700', '900'] })


export default function RootLayout({ children, }: { children: React.ReactNode }) {

    // const { state, dispatch }: IContext = useContext(ContextApi)

    // useEffect(() => {
    //     const user = Cookies.get('userData')
    //     if (user) {
    //         const parsed_user = JSON.parse(user)
    //         console.log(parsed_user)
    //         dispatch({ type: 'AUTH', payload: parsed_user })
    //     }
    //     else {
    //         console.log('logoutttt')
    //         dispatch({ type: 'AUTH_LOGOUT' })
    //     }
    // }, [dispatch])

    return (
        <html lang="en" className={`${roboto.className}`}>
            <body>
                <CreateContext>
                    <Header />
                    {children}
                </CreateContext>
            </body>
        </html>
    )
}
